from PyQt5 import QtCore, QtGui, QtWidgets

import InterfazBorrarMascota
import InterfazBuscarCliente
import InterfazCrearMascota
import InterfazEditarCliente
import InterfazElegirMascota
import main
class Editar(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(991, 521)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BotonEditarMascota = QtWidgets.QPushButton(self.centralwidget)
        self.BotonEditarMascota.setGeometry(QtCore.QRect(310, 330, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.BotonEditarMascota.setFont(font)
        self.BotonEditarMascota.setTabletTracking(True)
        self.BotonEditarMascota.setAcceptDrops(True)
        self.BotonEditarMascota.setStyleSheet("background-color: #00A2FF;\n"
        "border-style: solid;\n"
        "border-color: black;\n"
        "border-width: 3px;\n"
        "border-radius: 20px;")
        self.BotonEditarMascota.setAutoRepeatDelay(300)
        self.BotonEditarMascota.setObjectName("BotonEditarMascota")
        self.BotonBorrarMascota = QtWidgets.QPushButton(self.centralwidget)
        self.BotonBorrarMascota.setGeometry(QtCore.QRect(760, 330, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.BotonBorrarMascota.setFont(font)
        self.BotonBorrarMascota.setTabletTracking(True)
        self.BotonBorrarMascota.setAcceptDrops(True)
        self.BotonBorrarMascota.setStyleSheet("background-color: #00A2FF;\n"
        "border-style: solid;\n"
        "border-color: black;\n"
        "border-width: 3px;\n"
        "border-radius: 20px;")
        self.BotonBorrarMascota.setAutoRepeatDelay(300)
        self.BotonBorrarMascota.setObjectName("BotonBorrarMascota")
        self.ImgBorrar = QtWidgets.QLabel(self.centralwidget)
        self.ImgBorrar.setGeometry(QtCore.QRect(770, 230, 101, 101))
        self.ImgBorrar.setStyleSheet("background-color: no color;")
        self.ImgBorrar.setText("")
        self.ImgBorrar.setPixmap(QtGui.QPixmap("alo/Borrar.png"))
        self.ImgBorrar.setScaledContents(True)
        self.ImgBorrar.setObjectName("ImgBorrar")
        self.ImgCliente = QtWidgets.QLabel(self.centralwidget)
        self.ImgCliente.setGeometry(QtCore.QRect(100, 230, 91, 91))
        self.ImgCliente.setStyleSheet("background-color: no color;")
        self.ImgCliente.setText("")
        self.ImgCliente.setPixmap(QtGui.QPixmap("alo/Cliente.png"))
        self.ImgCliente.setScaledContents(True)
        self.ImgCliente.setObjectName("ImgCliente")
        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(90, 50, 781, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Titulo.setFont(font)
        self.Titulo.setStyleSheet("background-color: white;\n"
        "border-style: solid;\n"
        "border-color: black;\n"
        "border-width: 3px;")
        self.Titulo.setTextFormat(QtCore.Qt.AutoText)
        self.Titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.Titulo.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.Titulo.setObjectName("Titulo")
        self.Fondo = QtWidgets.QLabel(self.centralwidget)
        self.Fondo.setGeometry(QtCore.QRect(0, 0, 991, 521))
        self.Fondo.setMouseTracking(False)
        self.Fondo.setAcceptDrops(False)
        self.Fondo.setAutoFillBackground(False)
        self.Fondo.setStyleSheet("background-color: #F1F1F1;\n"
        "border-style: solid;\n"
        "border-color: #00A2FF;\n"
        "border-width: 10px;")
        self.Fondo.setText("")
        self.Fondo.setObjectName("Fondo")
        self.BotonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.BotonAtras.setGeometry(QtCore.QRect(920, 460, 41, 41))
        self.BotonAtras.setStyleSheet("background-color: no color;\n"
        "border-style: solid;\n"
        "border-width: 0px;")
        self.BotonAtras.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("alo/Atras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BotonAtras.setIcon(icon)
        self.BotonAtras.setIconSize(QtCore.QSize(40, 40))
        self.BotonAtras.setObjectName("BotonAtras")
        self.BotonAgregarMascota = QtWidgets.QPushButton(self.centralwidget)
        self.BotonAgregarMascota.setGeometry(QtCore.QRect(530, 330, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.BotonAgregarMascota.setFont(font)
        self.BotonAgregarMascota.setTabletTracking(True)
        self.BotonAgregarMascota.setAcceptDrops(True)
        self.BotonAgregarMascota.setStyleSheet("background-color: #00A2FF;\n"
        "border-style: solid;\n"
        "border-color: black;\n"
        "border-width: 3px;\n"
        "border-radius: 20px;")
        self.BotonAgregarMascota.setAutoRepeatDelay(300)
        self.BotonAgregarMascota.setObjectName("BotonAgregarMascota")
        self.BotonEditarCliente = QtWidgets.QPushButton(self.centralwidget)
        self.BotonEditarCliente.setGeometry(QtCore.QRect(90, 330, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.BotonEditarCliente.setFont(font)
        self.BotonEditarCliente.setTabletTracking(True)
        self.BotonEditarCliente.setAcceptDrops(True)
        self.BotonEditarCliente.setStyleSheet("background-color: #00A2FF;\n"
        "border-style: solid;\n"
        "border-color: black;\n"
        "border-width: 3px;\n"
        "border-radius: 20px;")
        self.BotonEditarCliente.setAutoRepeatDelay(300)
        self.BotonEditarCliente.setObjectName("BotonEditarCliente")
        self.ImgAgregar = QtWidgets.QLabel(self.centralwidget)
        self.ImgAgregar.setGeometry(QtCore.QRect(550, 240, 81, 81))
        self.ImgAgregar.setStyleSheet("background-color: no color;")
        self.ImgAgregar.setText("")
        self.ImgAgregar.setPixmap(QtGui.QPixmap("alo/Agregar.png"))
        self.ImgAgregar.setScaledContents(True)
        self.ImgAgregar.setObjectName("ImgAgregar")
        self.ImgMascota = QtWidgets.QLabel(self.centralwidget)
        self.ImgMascota.setGeometry(QtCore.QRect(320, 230, 101, 101))
        self.ImgMascota.setStyleSheet("background-color: no color;")
        self.ImgMascota.setText("")
        self.ImgMascota.setPixmap(QtGui.QPixmap("alo/Mascota.png"))
        self.ImgMascota.setScaledContents(True)
        self.ImgMascota.setObjectName("ImgMascota")
        self.ImgEditar2 = QtWidgets.QLabel(self.centralwidget)
        self.ImgEditar2.setGeometry(QtCore.QRect(170, 230, 21, 21))
        self.ImgEditar2.setStyleSheet("background-color: no color;")
        self.ImgEditar2.setText("")
        self.ImgEditar2.setPixmap(QtGui.QPixmap("alo/Editar2.png"))
        self.ImgEditar2.setScaledContents(True)
        self.ImgEditar2.setObjectName("ImgEditar2")
        self.ImgEditar = QtWidgets.QLabel(self.centralwidget)
        self.ImgEditar.setGeometry(QtCore.QRect(410, 230, 21, 21))
        self.ImgEditar.setStyleSheet("background-color: no color;")
        self.ImgEditar.setText("")
        self.ImgEditar.setPixmap(QtGui.QPixmap("alo/Editar2.png"))
        self.ImgEditar.setScaledContents(True)
        self.ImgEditar.setObjectName("ImgEditar")
        self.Fondo.raise_()
        self.BotonEditarMascota.raise_()
        self.BotonBorrarMascota.raise_()
        self.ImgBorrar.raise_()
        self.ImgCliente.raise_()
        self.Titulo.raise_()
        self.BotonAtras.raise_()
        self.BotonAgregarMascota.raise_()
        self.BotonEditarCliente.raise_()
        self.ImgAgregar.raise_()
        self.ImgMascota.raise_()
        self.ImgEditar2.raise_()
        self.ImgEditar.raise_()
        self.TxtNombre = QtWidgets.QLabel(self.centralwidget)
        self.TxtNombre.setGeometry(QtCore.QRect(300, 400, 371, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.TxtNombre.setFont(font)
        self.TxtNombre.setStyleSheet("background-color: no color;\n"
        "color:black;")
        self.TxtNombre.setTextFormat(QtCore.Qt.AutoText)
        self.TxtNombre.setAlignment(QtCore.Qt.AlignCenter)
        self.TxtNombre.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.TxtNombre.setObjectName("TxtNombre")
        self.TxtRut = QtWidgets.QLabel(self.centralwidget)
        self.TxtRut.setGeometry(QtCore.QRect(300, 420, 371, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.TxtRut.setFont(font)
        self.TxtRut.setStyleSheet("background-color: no color;\n"
        "color:black;")
        self.TxtRut.setTextFormat(QtCore.Qt.AutoText)
        self.TxtRut.setAlignment(QtCore.Qt.AlignCenter)
        self.TxtRut.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.TxtRut.setObjectName("TxtRut")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.BotonAtras.clicked.connect(lambda : self.cambio2(MainWindow,InterfazBuscarCliente.BuscarCliente,True))
        self.BotonEditarCliente.clicked.connect(lambda: self.cambio(MainWindow, InterfazEditarCliente.EditarCliente))
        self.BotonBorrarMascota.clicked.connect(lambda: self.cambio(MainWindow, InterfazBorrarMascota.BorrarMascota))
        self.BotonEditarMascota.clicked.connect(lambda: self.cambio2(MainWindow, InterfazElegirMascota.ElegirMascota,False))
        self.BotonAgregarMascota.clicked.connect(lambda: self.cambio2(MainWindow, InterfazCrearMascota.CrearMascota,False))

    def cambio2(self, MainWindow,Interfaz,Bandera):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Interfaz()
        self.ui.setupUi(self.ventana,Bandera)
        self.ventana.show()
        MainWindow.close()

    def cambio(self, MainWindow,Interfaz):
        self.ventana = QtWidgets.QMainWindow()
        self.ui = Interfaz()
        self.ui.setupUi(self.ventana)
        self.ventana.show()
        MainWindow.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventana Editar"))
        self.BotonEditarMascota.setText(_translate("MainWindow", "EDITAR MASCOTA"))
        self.BotonBorrarMascota.setText(_translate("MainWindow", "BORRAR MASCOTA"))
        self.Titulo.setText(_translate("MainWindow", "EDITAR"))
        self.BotonAgregarMascota.setText(_translate("MainWindow", "AGREGAR MASCOTA"))
        self.BotonEditarCliente.setText(_translate("MainWindow", "EDITAR CLIENTE"))
        self.TxtNombre.setText(_translate("MainWindow", f"Cliente: {main.cliente.nombreCompleto}"))
        self.TxtRut.setText(_translate("MainWindow", f"Rut: {main.cliente.rut}"))

